version: "3.9"

services:
  api:
    build: 
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:22042004@postgres:5432/banking
      NODE_ENV: prod
      PORT: 7000
    ports:
      - "4040:7000"
  postgres:
    image: postgres:12
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 22042004
      POSTGRES_DB: banking

